# Generated by Django 4.1.7 on 2023-03-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
